#pragma once

#define CPPMARKUP_OBJECT(NAME)
#define CPPMARKUP_OBJECT_EX(NAME, DISPLAYNAME)
#define CPPMARKUP_EMBED_OBJECT_begin(NAME, DISPLAYNAME)
#define CPPMARKUP_EMBED_OBJECT_end(NAME)
#define CPPMARKUP_ELEMENT_EX(NAME, DISPLAYNAME, DEFAULTVALUE, FLAGS, DESCRIPTION)